name = "JuliaProject"
uuid = "eb6a66cd-f301-41d1-8d08-a7e9d1ec353e"
authors = ["marleenlki <marleen.lukei@bertelsmann.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
